### ISSUE TITLE
Can't Build for Release

### ISSUE THREAD

**Issue by scout208** [ms-iot/RPi-UEFI#20]
According to the readme, to build for release:

> go to: %EDK_ROOT%\Conf\target.txt and locate the line with TARGET = DEBUG and change that to TARGET = RELEASE and rebuild. The output path DEBUG_ARMGCC part will change to RELEASE_ARMGCC.

However the current version of the repo doesn't have a conf\target.txt file. How are we supposed to build for Release now? Thanks.

**Comment by christopherco** [comment]
The EDK2 build system is a bit odd. Basically Conf\target.txt gets generated at build time from the template in BaseTools\Conf\target.template. This only happens if there isn't a target.txt file already present from a previous build. If there is a target.txt file already there, the build system will just use it as is.

So to build Release, I recommend one of two methods:
1. You could edit the BaseTools\Conf\target.template file, delete the Conf\target.txt file if present, and build. This should force the generation of a new target.txt file with your Release setting.
1. Or run the build once, edit Conf\target.txt with Release, and rebuild. The build system will use your current Conf\target.txt for the rebuild.

**Comment by scout208** [comment]
@christopherco Okay, I built it once in Debug then saw the conf\target.txt got created and then I was able to change to release. Thanks.
